const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
function toast(m){const e=$('#toast');if(!e)return;e.textContent=m;e.classList.add('show');clearTimeout(window.__t);window.__t=setTimeout(()=>e.classList.remove('show'),2200)}
const b=$('.menu-btn'),n=$('.nav-links')||$('.nav nav');if(b&&n){b.addEventListener('click',()=>{n.classList.toggle('open');b.setAttribute('aria-expanded',String(n.classList.contains('open')))});$$('a',n).forEach(a=>a.addEventListener('click',()=>n.classList.remove('open')))}
if('IntersectionObserver'in window){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.08});$$('.reveal').forEach(e=>io.observe(e))}else $$('.reveal').forEach(e=>e.classList.add('visible'));
$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>{const f=b.dataset.filter;$$('[data-filter]').forEach(x=>x.classList.remove('active'));b.classList.add('active');$$('[data-cat]').forEach(c=>c.classList.toggle('hidden',f!=='all'&&c.dataset.cat!==f))}));
function brief(d){return['AN KHƯƠNG MEDIA — BRIEF YÊU CẦU','--------------------------------','Họ tên: '+(d.get('name')||''),'Công ty: '+(d.get('company')||''),'Điện thoại: '+(d.get('phone')||''),'Email: '+(d.get('email')||''),'Dịch vụ: '+(d.get('service')||''),'Ngày dự kiến: '+(d.get('event_date')||''),'Ngân sách: '+(d.get('budget')||''),'Footage / Drive: '+(d.get('footage')||''),'Yêu cầu: '+(d.get('message')||'')].join('\n')}
const f=$('#leadForm');if(f)f.addEventListener('submit',e=>{e.preventDefault();const t=brief(new FormData(f)),o=$('#briefOutput'),actions=$('#briefActions'),sms=$('#smsBriefBtn');o.textContent=t;o.hidden=false;if(actions)actions.hidden=false;if(sms)sms.href='sms:+84868054679?body='+encodeURIComponent(t);toast('Đã tạo brief.')});
const cp=$('#copyBriefBtn');if(cp)cp.addEventListener('click',async()=>{const o=$('#briefOutput');try{await navigator.clipboard.writeText(o.textContent);toast('Đã sao chép brief.')}catch{toast('Hãy chọn và sao chép nội dung brief.')}});
(function(){const q=new URLSearchParams(location.search),v=q.get('service'),s=document.querySelector('select[name="service"]');if(!s)return;const map={'agency-white-label':'Agency / White-label','ai-skill':'AI Skill / Workflow / Prompt Pack','ai-app':'AI App / Automation','ai-business':'AI Business / Setup','ai-media-monthly':'AI Media Monthly'};if(map[v])s.value=map[v];})();

(function(){const q=new URLSearchParams(location.search),p=q.get('product'),m=document.querySelector('textarea[name="message"]');if(p&&m&&!m.value){m.value='Tôi quan tâm sản phẩm: '+p+'. Vui lòng tư vấn gói phù hợp.';}})();
